#!/usr/bin/env bash

# Check if formatting and tests pass before allowing commits.

STATUS=0

./run_formatter.sh

STATUS=$(($STATUS + $?))

if [ "$STATUS" != 0 ]; then
    printf -- "Formatting Checks failed, aborting commit\n"
    exit $STATUS
fi

printf -- "\n\n"
./run_tests.sh

STATUS=$(($STATUS + $?))

if [ "$STATUS" != 0 ]; then
    printf -- "Tests failed, aborting commit\n"
    exit $STATUS
fi

exit 0
